# cv2 type stub
from typing import Any

def imread(filename: str, flags: int = ...) -> Any: ...
def imwrite(filename: str, img: Any, params: Any = ...) -> bool: ...
def cvtColor(src: Any, code: int) -> Any: ...
def Laplacian(src: Any, ddepth: int) -> Any: ...
def meanStdDev(src: Any) -> Any: ...
def inRange(src: Any, lowerb: Any, upperb: Any) -> Any: ...
def countNonZero(src: Any) -> int: ...
def resize(src: Any, dsize: Any, fx: float = ..., fy: float = ..., interpolation: int = ...) -> Any: ...

COLOR_BGR2GRAY: int = 6
COLOR_BGR2HSV: int = 40
COLOR_RGB2BGR: int = 4
CV_64F: int = 6
