from typing import Any

ndarray: Any
float32: Any
uint8: Any
int64: Any

def array(data: Any, dtype: Any = ...) -> Any: ...
def asarray(data: Any, dtype: Any = ...) -> Any: ...
def zeros(shape: Any, dtype: Any = ...) -> Any: ...
def ones(shape: Any, dtype: Any = ...) -> Any: ...
def clip(a: Any, a_min: Any, a_max: Any) -> Any: ...
def mean(a: Any, axis: Any = ...) -> float: ...
def std(a: Any, axis: Any = ...) -> float: ...
def argmax(a: Any, axis: Any = ...) -> int: ...
def maximum(x1: Any, x2: Any) -> Any: ...
def minimum(x1: Any, x2: Any) -> Any: ...

class _Random:
    def uniform(self, low: float = ..., high: float = ..., size: Any = ...) -> Any: ...
    def randint(self, low: int, high: int = ..., size: Any = ..., dtype: Any = ...) -> Any: ...

random: _Random
